### PR TITLE
added couchbase probe for couchnode package

### PR DESCRIPTION
**Pull request by astub**
#494

### CODE REVIEW

**Comment by astub** [comment]
I'm not sure what is making codecov fail.

**Comment by tobespc** [comment]
@astub before we can accept your change request, please can you read and accept 

https://github.com/RuntimeTools/appmetrics/blob/master/CONTRIBUTING.md

**Comment by sjanuary** [comment]
@astub if your test can be run without needing a database to be set up (looks like a mock one?) then you can add it to the list of tests we run in package.json  https://github.com/RuntimeTools/appmetrics/blob/master/package.json#L32. We call out the tests individually because we have some probe tests that require a service setting up like a database so we don't run those by default. That would also fix the codecov decrease.

**Comment by astub** [comment]
@sjanuary Hi. It uses couchbase.Mock so it does not need a couchbase server. I'm unsure what else i'm missing for this PR.

**Comment by sjanuary** [comment]
@astub - you need to rebase as master has changed since this PR and there are conflicts. Also if you rename your test file to end in "tests.js" then it will be run automatically - see https://github.com/RuntimeTools/appmetrics/blob/master/package.json#L32

**Comment by astub** [comment]
@sjanuary Thanks for your feedback. Anything else I need to improve/fix?

**Comment by sjanuary** [comment]
@astub please could you also add a description the couchbase event to the Readme?  It needs to go in the table at the start and also [here](https://github.com/RuntimeTools/appmetrics/blob/master/README.md#api-dependency-events-probes).

**Comment by astub** [comment]
closing this as its a copy of #506

**Pull request closed without merging**
