### PR TITLE
Support Node for z/OS

### PR DESCRIPTION
**Pull request by mattcolegate**
Please squash and merge

### CODE REVIEW

**Comment by stalleyj** [comment]
@mattcolegate we need to skip the headless tests as these won't pass on z/OS at the moment and make sure headless fails gracefully on z/OS.

**Comment by mattcolegate** [comment]
I think what's happened here is that I've straight commented-out headless functionality in `index.js` and `appmetrics.cpp` - will need to surround those statements with a check for ZOS / os390.
I'll also put that check into the headless tests.

**Comment by mattcolegate** [comment]
@stalleyj Travis builds now pass, ready for re-review

**Comment by stalleyj** [comment]
Travis is passing so let's get this in and built on the other platforms.

**Pull request merged**
