### PR TITLE
Don't force MQTT broker to on

### LINKED ISSUE #209: disable mqtt
This log message appears despite configuration:
```
[Wed May  4 09:58:44 2016] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
```

Configuration:
```
com.ibm.diagnostics.healthcenter.mqtt=off
```

Am I wrong in assuming that this configuration should result in no attempt to connect to the broker?  Is there another configuration I should be using if I only want to use the API?

### LINKED ISSUE #305: Should be possible to switch off connecting to MQTT broker
Not every user will want appmetrics to automatically connect to an MQTT broker on the default port and start sending data. E.g. they may be running an MQTT broker for something else. It should be possible to disable this.

### PR DESCRIPTION
**Pull request by sjanuary**
fixes #305 and fixes #209

### CODE REVIEW

**Comment by tobespc** [comment]
LGTM

**Comment by sam-github** [comment]
Does it still default to "on"?

**Comment by tobespc** [comment]
Yes, still defaults to on

**Comment by sjanuary** [comment]
See https://github.com/RuntimeTools/appmetrics/blob/master/appmetrics.properties#L2

**Pull request merged**
