### PR TITLE
Incorporate node-heapdump into appmetrics

### PR DESCRIPTION
**Pull request by sjanuary**

### CODE REVIEW

**Comment by sam-github** [comment]
Intention is this be used as `require("appmetrics/heapdump")`?

**Comment by sjanuary** [comment]
@sam-github It can be used like that, but I think the main intention is that it will be built-in for appmetrics to use, the fact that it can be used standalone is more of a side effect.

**Comment by sam-github** [comment]
@sjanuary OK, so it won't be advertised to appmetrics users?

I want to use it in strong-supervisor, it will allow us to remove a dependency on heapdump, which is a compiled module. That's OK, right?

**Comment by sjanuary** [comment]
That's fine, it should work exactly the same as heapdump at the 0.3.7 level, unit tests run fine  We may be out of date for a bit if any updates go into heapdump, but it's a pretty mature codebase so I don't think we need to worry too much about that.

**Comment by mattcolegate** [comment]
LGTM

**Pull request merged**
