### PR TITLE
Add information for appmetrics-dash summary panel.

### PR DESCRIPTION
**Pull request by hhellyer**
- Add max used heap and total proportion of time in gc to gc messages.
- Add mean cpu usage stats.

### CODE REVIEW

**Comment by sjanuary** [comment]
@hhellyer - can the tests be updated to check for these new properties? See https://github.com/RuntimeTools/appmetrics/blob/master/tests/api_tests.js

**Comment by tobespc** [comment]
typically, you process the data where you want to use it so doing the work in the dashboard would fit that model.  However, are there any other places (thinking of our current work) where we would also want to use this as part of feedback loop ?

**Comment by sjanuary** [comment]
@tobespc if we need to write another engine to collect data that isn't part of the dashboard, then that probably wouldn't go into appmetrics base anyway. We could reconsider if needed.

**Comment by sjanuary** [comment]
@hhellyer - can this be closed? I think the work was done in appmetrics-dash in the end?

**Comment by stalleyj** [comment]
Closing, agreed with Howard.

**Pull request closed without merging**
