### PR TITLE
Added MySQL Pool metrics

### PR DESCRIPTION
**Pull request by rwky**
The current MySQL probe doesn't work with MySQL Pools, this enables that functionality.

### CODE REVIEW

**Comment by tobespc** [comment]
@rwky before we can accept your pull request, please can you fill out a CLA agreement https://github.com/RuntimeTools/appmetrics/blob/master/CONTRIBUTING.md

**Comment by rwky** [comment]
Would love to except it says I need to print, sign and scan the doc, I won't be any where near my printer/scanner until August. Can I digitally sign it?

**Comment by NikCanvin** [comment]
@rwky yes, assuming it looks OK, that should be fine, thanks.

**Comment by rwky** [comment]
Attached doc gpg signed will that do?

[Archive.zip](https://github.com/RuntimeTools/appmetrics/files/380663/Archive.zip)

**Comment by tobespc** [comment]
@rwky Can you send that document to  jimmail@uk.ibm.com.  I had a look but couldn't see any details in it related to you

**Comment by rwky** [comment]
Check the .asc file it has my gpg signature.

**Comment by NikCanvin** [comment]
Sorry @rwky, I'm not able to resolve your .asc file to the personal details requested in the CLA form.. I suggest you print it down, complete, scan in/photo it, then send to jimmail@uk.ibm.com .
(I realise this process is a little awkward, I'm investing moving to the CLA process built into github, hopefully this will be much smoother in future).

**Comment by rwky** [comment]
Forget it I stopped using this module it caused issues when in production.

**Pull request closed without merging**
