### PR TITLE
Don't block Node shutdown

### PR DESCRIPTION
**Pull request by sjanuary**
Bug in headless implementation was blocking node from exiting with appmetrics running

### CODE REVIEW

**Comment by tobespc** [comment]
LGTM

**Comment by sam-github** [comment]
Should be easy to unit test.

**Comment by sjanuary** [comment]
@sam-github - how would you write that test?  This was caught by our system tests, but they're run from a shell script.

**Comment by sam-github** [comment]
I think something like test/test-no-refs-leaked.js:

```
require('../').start();
```

is basically the test, and maybe you don't need `.start()`? You'd add the test to package.json's `test` property.

You'd want to make it be valid tap, though, maybe add a `tap.assert(true);` so that at least one assertion shows up.

You'd want to make this

**Comment by sam-github** [comment]
Actually, looks like the bug may manifest only on calls to start, so you might need that.

**Pull request merged**
