### PR TITLE
fix `exports.emit is not a function`

### PR DESCRIPTION
**Pull request by nqvst**
seems that the module keyword was forgotten
i accept the "IBM Runtimes Tools Contributor License Agreement".

### CODE REVIEW

**Comment by sam-github** [comment]
Note that this can only happen when multiple appmetrics instances exist, and second one is using the previously required instance, a situation that is hard to arrange in unit tests.

https://github.com/RuntimeTools/appmetrics/blob/master/index.js#L127 should be `exports = module.exports = global.Appmetrics;`, keeping the two always identical avoids this kind of error.

**Comment by nqvst** [comment]
@sam-github  I'm sorry, but I don't understand what you mean. is exports defined somewhere? I thought it was just a typo.
do you want me to change back and then do `exports = module.exports = global.Appmetrics;`

**Comment by sam-github** [comment]
https://nodejs.org/api/modules.html#modules_exports

I think your change makes things more consistent, and the change I suggest would make the code less fragile.

**Comment by sjanuary** [comment]
@sam-github isn't `exports` already an alias for `module.exports` in Node.js?

**Comment by nqvst** [comment]
i don't think so. in my repl node 6 and 8 it gives me `ReferenceError: exports is not defined`

**Comment by sjanuary** [comment]
@nqvst see [https://nodejs.org/api/modules.html#modules_exports_shortcut](https://nodejs.org/api/modules.html#modules_exports_shortcut), which is why the current implementation works.  Sam is right though, if we reassign module.exports we should also reassign exports according to that link.

**Comment by nqvst** [comment]
@sjanuary ok, thanks for the info!

**Comment by sam-github** [comment]
>  isn't exports already an alias for module.exports in Node.js?

They aren't true aliases in the sense if you change one the other gets somehow changed too. But they do start out with the same value assigned to both, and are both user-assignable, so if you assign to one and not the other then they no longer have the same value.

**Pull request merged**
