### PR TITLE
#496 fix python3 error

### PR DESCRIPTION
**Pull request by darky**

### CODE REVIEW

**Comment by tobespc** [comment]
@darky Thanks for this, before we can accept please can you accept the CLA agreement first.

https://github.com/RuntimeTools/appmetrics/blob/master/CONTRIBUTING.md

**Comment by darky** [comment]
fix https://github.com/RuntimeTools/appmetrics/issues/496

**Comment by tobespc** [comment]
@darky Please can you confirm the following from the CLA
"
You must include in the Pull Request a statement of Your acceptance of this CLA. As used in this CLA: (i) "You" (or "Your") shall mean the entity that is making this Agreement with IBM; (ii)"Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is submitted by You to IBM for inclusion in, or documentation of, any of the IBM GitHub repositories; (iii) "Submit" (or "Submitted") means any form of communication sent to IBM (e.g. the content You post in a GitHub Issue or submit as part of a GitHub Pull Request)."

**Comment by darky** [comment]
@tobespc, yep! I include my ID in *AUTHORS.md*, which mean that I agree CLA if I properly understand Contibuting guide https://github.com/RuntimeTools/appmetrics/blob/master/CONTRIBUTING.md

**Comment by sjanuary** [comment]
Merged

**Pull request merged**
